CREATE VIEW MEDICINE_NO_PRESC
AS SELECT NAME, FORM FROM FN72082.MEDICINE WHERE PRESCRIPTION LIKE 'FALSE';

CREATE VIEW SELLER_PHONE
AS SELECT PHONE FROM FN72082.SELLER;

CREATE VIEW PRODUCT_UNDER_10_LEVA
AS SELECT NAME, FIRM FROM FN72082.PRODUCTS
WHERE PRICE < 10;