SET SCHEMA FN72082;

CREATE TABLE PRODUCTS (
    PRICE DOUBLE NOT NULL,
    NAME CHAR(20) NOT NULL PRIMARY KEY,
    FIRM VARCHAR(20) NOT NULL
);
CREATE TABLE NONMEDICINE (
    NAME CHAR(20) NOT NULL PRIMARY KEY,
    TYPE VARCHAR(10),
    FOREIGN KEY (NAME) REFERENCES PRODUCTS (NAME)
);

CREATE TABLE MEDICINE (
    NAME CHAR(20) NOT NULL PRIMARY KEY,
    FORM CHAR CHECK (FORM IN ('P', 'S', 'T', 'G')) NOT NULL,
    PRESCRIPTION CHAR(5) NOT NULL CHECK (PRESCRIPTION IN ('TRUE', 'FALSE')),
    FOREIGN KEY (NAME) REFERENCES PRODUCTS (NAME)
);

CREATE TABLE MANAGERS (
    PHONE CHAR(13) CHECK(PHONE LIKE '0%'),
    NAME CHAR(50) NOT NULL,
    CITY CHAR(50) NOT NULL,
    PRIMARY KEY (NAME, CITY)
);

CREATE TABLE PHARMACIES (
    NAME CHAR(20) NOT NULL PRIMARY KEY,
    ADDRESS VARCHAR(100) NOT NULL,
    M_NAME CHAR(50) NOT NULL,
    CITY CHAR(50) NOT NULL,
    FOREIGN KEY (M_NAME, CITY) REFERENCES MANAGERS(NAME, CITY)
);

CREATE TABLE SELLER (
    NAME VARCHAR(50) NOT NULL,
    PHONE CHAR(13) CHECK(PHONE LIKE '0%'),
    SNUM INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    P_NAME CHAR(20) NOT NULL
);

ALTER TABLE SELLER
ADD FOREIGN KEY (P_NAME) REFERENCES PHARMACIES(NAME);

CREATE TABLE SUPPLIERS (
    NAME CHAR(20) NOT NULL PRIMARY KEY,
    CITY VARCHAR(10)
);

CREATE TABLE SUPPLIES (
    S_NAME CHAR(20) NOT NULL,
    P_NAME CHAR(20) NOT NULL,
    PRIMARY KEY(S_NAME, P_NAME),
    FOREIGN KEY(S_NAME) REFERENCES SUPPLIERS(NAME),
    FOREIGN KEY(P_NAME) REFERENCES PHARMACIES(NAME)
);

CREATE TABLE DELIVERS (
    S_NAME CHAR(20) NOT NULL,
    P_NAME CHAR(20) NOT NULL,
    PRIMARY KEY(S_NAME, P_NAME),
    FOREIGN KEY(S_NAME) REFERENCES SUPPLIERS(NAME),
    FOREIGN KEY(P_NAME) REFERENCES PRODUCTS(NAME)
);

CREATE TABLE SELLS (
    QUANTITY INT,
    PH_NAME CHAR(20) NOT NULL,
    PR_NAME CHAR(20) NOT NULL,
    PRIMARY KEY(PH_NAME, PR_NAME),
    FOREIGN KEY(PH_NAME) REFERENCES PHARMACIES(NAME),
    FOREIGN KEY(PR_NAME) REFERENCES PRODUCTS(NAME)
);

SELECT NAME FROM FN72082.MEDICINE WHERE PRESCRIPTION LIKE 'TRUE%';

INSERT INTO PRODUCTS(PRICE, NAME, FIRM) VALUES (10, 'KLACID', 'MYLAN');
